# Generated by Django 4.1.3 on 2022-11-23 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_inventory_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bar_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
