# Generated by Django 4.1.3 on 2022-11-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_rename_item_name_inventory_item_bc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='prod_invt',
        ),
    ]
